# k8s/config.yaml

# 1. SECRET : Stockage des identifiants de la base de données
# Les valeurs doivent être encodées en base64 (ex: echo -n "cookbook_user" | base64)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  POSTGRES_USER: Y29va2Jvb2tfdXNlcg== # cookbook_user
  POSTGRES_PASSWORD: c3Ryb25nX3Bhc3N3b3Jk # strong_password
  POSTGRES_DB: Y29va2Jvb2tfZGI= # cookbook_db

---

# 2. CONFIGMAP : Stockage des variables de configuration non-sensibles
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Doit correspondre à la variable VITE_API_URL du frontend
  API_V1_URL: "http://cookbook-backend-service:8000/api/v1"