# k8s/config.yaml

# 1. SECRET : Stockage des identifiants de la base de données
# Les valeurs doivent être encodées en base64 (ex: echo -n "cookbook_user" | base64)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  POSTGRES_USER: Y29va2Jvb2tfdXNlcg== # cookbook_user
  POSTGRES_PASSWORD: c3Ryb25nX3Bhc3N3b3Jk # strong_password
  POSTGRES_DB: Y29va2Jvb2tfZGI= # cookbook_db

---

# 2. CONFIGMAP : Stockage des variables de configuration non-sensibles
apiVersion: v1
kind: ConfigMap
metadata:
  name: cookbook-config
data:
  # URL pour la connexion à la base de données
  DATABASE_URL: "postgresql://user:password@cookbook-db-service/cookbookdb"
  
  # URL de l'API (utilisée par le frontend)
  API_V1_URL: "http://cookbook-backend-service:8000/api/v1"

  # Origines CORS autorisées (séparées par des virgules)
  CORS_ORIGINS: "http://173.212.228.118:8090,http://localhost:5173,http://127.0.0.1:5173"