name: CD - Deploy to VPS (via SSH)

on:
  workflow_run:
    workflows: ["CI - Build and Push Images"]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  deploy-to-vps:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait for images to be available
        run: echo "Images built and pushed. Proceeding to deploy..."

      - name: Copy deployment script to VPS and execute
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: ./deploy/deploy_vps.sh
          target: ~/deploy_vps.sh

      - name: Run deployment script on VPS via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            chmod +x ~/deploy_vps.sh
            ~/deploy_vps.sh
