name: CI - Build and Push Images

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set IMAGE_OWNER (lowercase)
        run: |
          # Ensure image owner is lowercase to satisfy Docker/OCI requirements
          echo "IMAGE_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/cookbook-app-backend:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_OWNER }}/cookbook-app-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/cookbook-app-frontend:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_OWNER }}/cookbook-app-frontend:latest
