name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint (frontend + backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'


      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          npm ci

      - name: Run frontend linter
        working-directory: frontend
        run: |
          npm run lint

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dev tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run backend linter
        run: |
          flake8 backend

  deploy:
    name: Deploy to VPS
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/project_kub_malick
            git pull origin main
            docker build -t cookbook-app-backend:latest ./backend
            docker build -t cookbook-app-frontend:latest ./frontend
            kind load docker-image cookbook-app-backend:latest
            kind load docker-image cookbook-app-frontend:latest
            kubectl rollout restart deployment cookbook-backend-deployment
            kubectl rollout restart deployment cookbook-frontend-deployment